name: gf_mobile
description: a native mobile application for greenfield

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  archive: ^3.3.8
  pull_down_button: ^0.9.3
  get:
  google_fonts:
  flashy_tab_bar2:
  flutter_staggered_grid_view: ^0.4.0
  flutter_expandable_fab:
  concentric_transition: ^1.0.3
  get_storage: ^2.1.1
  loading_indicator: ^3.1.1
  flutter_svg: ^1.1.6
  line_icons: ^2.0.3
  flutter_animated_icons: ^1.0.1
  tap_to_expand: ^0.6.1
  restart_app: ^1.2.1
  animated_theme_switcher:
  onboarding_overlay: ^3.2.1
  cupertino_onboarding: ^1.2.0
  flutter_onboarding_slider:
  gf_sdk:
    path: "../gf_sdk"

  web3dart:
  pointycastle:
  flutter_pin_code_fields:
  animated_digit: ^3.2.3
  animated_flip_counter: ^0.2.6
  local_auth:
  dio:
  url_launcher:
  provider: ^6.0.5
  date_format: ^2.0.7
  file_picker:
  mime:
  cached_network_image:
  sliding_up_panel2:
  fl_chart:
  flutter_inappwebview:
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/banners/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/gf_asset.png"
  min_sdk_android: 21